---
title: "Random generation: Inverse method. Examples "
author: ''
output:
  html_document:
    code_folding: show
    highlight: haddock
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 3
  pdf_document:
    toc: yes
---
# Statement: Random generation Inverse method: Exponential

## Aims and scope:


## Relationships with other distributions (shape parameter)

## Exponential random generator by Inverse method

```{r}

#tini <- proc.time()

lambda <- 3
nsim <- 10^5
set.seed(1)
U <- runif(nsim)
random_values <- -log(U)/lambda # -log(1-U)/lambda
#tiempo <- proc.time() - tini
#tiempo
## user system elapsed
## 0.00 0.01 0.02
hist(random_values, breaks = "FD", freq = FALSE, main= "Exponential Random generation",
xlim = c(0, 5), ylim = c(0, 2.5), col="blue")
curve(dexp(x, lambda), lwd = 2, add = TRUE, col="green")

```

# Statement: Random generation Inverse method: Weibull


## Aims and scope:


## Relationships with other distributions (shape parameter)


## Weibull random generator by Inverse method


# Statement: Random generation Inverse method: Cauchy

## Aims abd scope

## Relationships with other distributions 

  - The standard Cauchy distribution is the `Student t distribution (df=1)`. 
  
  - The standard Cauchy distribution also arises naturally as the **ratio of independent** `standard normal` variables.

## Cauchy random generator by Inverse method

# Statement: Random generation Inverse method: Gamma


## Aims and scope:


## Relationships with other distributions 


## Gamma random generator according to sum of exponential random variables


# Discrete distribution. Random generator

Give an algorithm to simulate the value of a random variable $X$ such that

  - $P(X=1)=0.35$
  
  - $P(X=2)=0.15$
  
  - $P(X=3)=0.4$
  
  - $P(X=4)=0.15$
  
## Discrete distribution. Random generator. Inverse method  


